language: python3
python:
  - "3.7"
install: "pip install -r src/requirements-dev.txt"
before_script:
  - cp .env.example .env
  - python src/manage.py migrate
script:
  - flake8 cmdbox
  - coverage run src/manage.py test --settings=cmdbox.tests_settings
after_success:
  - coveralls
