# Generated by Django 2.1.5 on 2019-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='France', max_length=120),
        ),
    ]
