# Generated by Django 2.1.5 on 2019-01-20 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190119_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 20, 3, 35, 50, 377688, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
